/**
 * Conceptos del Centro de Conocimiento (Fase 2).
 *
 * Contenido base a partir del "Diccionario Corporativo de Términos del Sistema
 * de Gestión" (versión 0, 27/08/2026, Violeta Martinez) — el glosario oficial
 * de la empresa, ya revisado y aprobado por Calidad. Los conceptos que tienen
 * definición en ese documento usan su texto oficial en `technicalDefinition`
 * tal cual; el resto del contenido (`simpleDefinition`, `avenidaExample`,
 * `whyItMatters`, `whatToDoIfDetected`) sigue redactado en lenguaje propio
 * para mantener el tono didáctico del portal. Los conceptos que NO están en
 * el diccionario oficial (categorías propias del SGC de Avenida+ como
 * "Oportunidad de Mejora" o "Reclamo") se mantienen con contenido propio,
 * alineado al vocabulario general de gestión de calidad.
 *
 * Ya no es contenido "borrador" para las pantallas de Conceptos — viene del
 * diccionario oficial. Las otras pantallas del Centro de Conocimiento (ISO
 * 9001, Calidad en 2 minutos, Comparador, FAQ) siguen con su badge de
 * borrador, pendientes de otra revisión aparte.
 */
import type { BadgeTone } from "@/components/ui/badge";

export type ConceptCategory =
  | "conceptos-de-calidad"
  | "riesgos-y-oportunidades"
  | "procesos"
  | "auditorias"
  | "mejora-continua"
  | "informacion-documentada"
  | "indicadores"
  | "clientes"
  | "proveedores"
  | "planificacion"
  | "liderazgo"
  | "diseno-y-desarrollo";

export const CONCEPT_CATEGORIES: Record<ConceptCategory, { label: string; tone: BadgeTone }> = {
  "conceptos-de-calidad": { label: "Conceptos de Calidad", tone: "violet" },
  "riesgos-y-oportunidades": { label: "Riesgos y oportunidades", tone: "amber" },
  procesos: { label: "Procesos", tone: "blue" },
  auditorias: { label: "Auditorías", tone: "green" },
  "mejora-continua": { label: "Mejora continua", tone: "violet" },
  "informacion-documentada": { label: "Información documentada", tone: "gray" },
  indicadores: { label: "Indicadores", tone: "blue" },
  clientes: { label: "Clientes", tone: "green" },
  proveedores: { label: "Proveedores", tone: "amber" },
  planificacion: { label: "Planificación", tone: "violet" },
  liderazgo: { label: "Liderazgo", tone: "gray" },
  "diseno-y-desarrollo": { label: "Diseño y Desarrollo", tone: "blue" },
};

export type Concept = {
  id: string;
  term: string;
  acronym?: string;
  category: ConceptCategory;
  technicalDefinition: string;
  simpleDefinition: string;
  avenidaExample: string;
  whyItMatters: string;
  whatToDoIfDetected: string;
  relatedIds: string[];
};

export const CONCEPTS: Concept[] = [
  {
    id: "no-conformidad",
    term: "No Conformidad",
    acronym: "NC",
    category: "conceptos-de-calidad",
    technicalDefinition: "Incumplimiento de un requisito.",
    simpleDefinition: "Algo que estaba definido y no pasó como tenía que pasar.",
    avenidaExample:
      "Un seller queda activo en el marketplace sin haber completado la validación de documentación bancaria que el procedimiento exige antes de habilitarlo.",
    whyItMatters:
      "Si no se identifica y corrige, la misma falla se repite y puede afectar a más clientes o procesos.",
    whatToDoIfDetected: "Reportala desde el portal: se registra la corrección inmediata y, si corresponde, se busca la causa raíz.",
    relatedIds: ["accion-correctiva", "correccion", "causa-raiz", "requisito"],
  },
  {
    id: "accion-correctiva",
    term: "Acción Correctiva",
    acronym: "AC",
    category: "mejora-continua",
    technicalDefinition: "Acción destinada a eliminar la causa de una No Conformidad y evitar que vuelva a ocurrir.",
    simpleDefinition:
      "No es \"arreglar el problema puntual\" (eso es la corrección): es resolver por qué pasó, para que no pase de nuevo.",
    avenidaExample:
      "Tras detectar varias NC por sellers activados sin documentación completa, se implementa un control automático que bloquea la activación hasta que el checklist esté 100% cargado.",
    whyItMatters: "Evita que el mismo tipo de falla se repita una y otra vez, en lugar de solo apagar incendios.",
    whatToDoIfDetected:
      "Se crea a partir de una NC ya registrada, con responsable, fecha objetivo y una verificación de eficacia posterior.",
    relatedIds: ["no-conformidad", "causa-raiz", "correccion", "verificacion-de-eficacia"],
  },
  {
    id: "accion-preventiva",
    term: "Acción Preventiva",
    acronym: "AP",
    category: "riesgos-y-oportunidades",
    technicalDefinition:
      "Acción tomada sobre una situación potencial, antes de que el problema llegue a ocurrir, generalmente a partir de un riesgo identificado.",
    simpleDefinition: "Actuar antes de que pase algo, no después.",
    avenidaExample:
      "Se detecta que un solo proveedor de conciliación bancaria concentra toda la operación crítica: se decide sumar un proveedor alternativo antes de que falle el único que existe hoy.",
    whyItMatters: "Es más barato y menos disruptivo prevenir que corregir después de que el problema ya afectó a alguien.",
    whatToDoIfDetected: "Si ves una situación que podría convertirse en un problema, reportala como riesgo u oportunidad de mejora.",
    relatedIds: ["riesgo", "oportunidad-de-mejora"],
  },
  {
    id: "correccion",
    term: "Corrección",
    category: "mejora-continua",
    technicalDefinition: "Acción tomada para eliminar una No Conformidad detectada.",
    simpleDefinition: "El parche rápido para frenar el problema ahora mismo.",
    avenidaExample:
      "Se detecta un pago duplicado a un seller: la corrección inmediata es reversar la transacción y avisar al área contable, aunque todavía no se sepa por qué pasó.",
    whyItMatters:
      "Contiene el impacto en el momento, pero por sí sola no evita que vuelva a suceder — para eso está la Acción Correctiva.",
    whatToDoIfDetected: "Aplicala apenas detectás el problema y registrala junto con la No Conformidad.",
    relatedIds: ["no-conformidad", "accion-correctiva"],
  },
  {
    id: "causa-raiz",
    term: "Causa raíz",
    category: "mejora-continua",
    technicalDefinition:
      "Causa fundamental que origina o permite la recurrencia de un problema o No Conformidad y sobre la cual resulta necesario actuar para evitar que vuelva a ocurrir.",
    simpleDefinition: "El motivo de fondo, no lo primero que se ve.",
    avenidaExample:
      "Un cliente reclama que su integración no sincroniza: el síntoma es \"falla la API\", pero la causa raíz puede ser que nunca se documentó el límite de rate limit al onboardear al cliente.",
    whyItMatters:
      "Si solo se corrige el síntoma, el problema reaparece con otra forma; atacar la causa evita la recurrencia.",
    whatToDoIfDetected: "Se analiza al gestionar una No Conformidad, antes de definir la Acción Correctiva.",
    relatedIds: ["no-conformidad", "accion-correctiva"],
  },
  {
    id: "eficacia",
    term: "Eficacia",
    category: "conceptos-de-calidad",
    technicalDefinition: "Grado en el que una acción planificada logra el resultado que se buscaba.",
    simpleDefinition: "¿Funcionó de verdad, o solo se hizo?",
    avenidaExample:
      "Se implementó un nuevo control de validación de sellers; la eficacia se confirma tres meses después si la tasa de NC por documentación incompleta bajó, no solo por haber puesto el control.",
    whyItMatters: "Sin medir eficacia, se puede confundir \"hicimos algo\" con \"el problema se resolvió\".",
    whatToDoIfDetected: "Se evalúa formalmente en la verificación de eficacia de cada Acción Correctiva.",
    relatedIds: ["verificacion-de-eficacia", "accion-correctiva"],
  },
  {
    id: "evidencia",
    term: "Evidencia",
    category: "informacion-documentada",
    technicalDefinition: "Información que permite demostrar la realización de una actividad o la obtención de un resultado.",
    simpleDefinition: "La prueba de que algo pasó, no solo el relato de que pasó.",
    avenidaExample:
      "Una captura de pantalla del error de integración, el ticket de Plane asociado y el mail al cliente son la evidencia de una No Conformidad y su corrección.",
    whyItMatters:
      "Permite demostrar ante una auditoría (o ante uno mismo) que el SGC realmente funciona, no solo que existe en el papel.",
    whatToDoIfDetected: "Adjuntá capturas, archivos o links cada vez que reportes o gestiones un registro del SGC.",
    relatedIds: ["informacion-documentada", "auditoria"],
  },
  {
    id: "hallazgo",
    term: "Hallazgo",
    category: "auditorias",
    technicalDefinition: "Resultado obtenido a partir de la evaluación de evidencias respecto de determinados criterios.",
    simpleDefinition: "Lo que un auditor encuentra al revisar cómo trabajamos.",
    avenidaExample:
      "En una auditoría interna al proceso de onboarding de bancos, se encuentra que dos legajos no tienen la validación de compliance firmada.",
    whyItMatters: "Es la forma en que una auditoría se traduce en mejora concreta: cada hallazgo puede generar una NC, una OM o una observación.",
    whatToDoIfDetected: "Se registra durante la auditoría y se convierte en un registro del SGC para su seguimiento.",
    relatedIds: ["auditoria", "no-conformidad", "oportunidad-de-mejora"],
  },
  {
    id: "indicador",
    term: "Indicador",
    category: "indicadores",
    technicalDefinition: "Medida cuantitativa que permite hacer seguimiento del desempeño de un proceso u objetivo a lo largo del tiempo.",
    simpleDefinition: "Un número que te dice si algo va bien o mal, y si va mejorando.",
    avenidaExample:
      "\"% de tickets de soporte B2B resueltos dentro del SLA acordado\", medido mensualmente por el área de Soporte.",
    whyItMatters: "Sin indicadores, las decisiones se toman por percepción en lugar de por datos.",
    whatToDoIfDetected: "Los indicadores se definen por proceso u objetivo; no se \"reportan\" como un problema puntual.",
    relatedIds: ["objetivo-de-calidad", "desempeno", "medicion"],
  },
  {
    id: "informacion-documentada",
    term: "Información documentada",
    category: "informacion-documentada",
    technicalDefinition:
      "Información que la organización debe controlar y mantener o conservar, junto con el medio que la contiene.",
    simpleDefinition: "Todo lo que está escrito y controlado: desde una política hasta el formulario que completás para reportar algo.",
    avenidaExample: "El Manual de Calidad, el instructivo de \"Cómo tipificar un ticket de Plane\" y el registro de una auditoría son información documentada.",
    whyItMatters: "Permite que el conocimiento no dependa de una sola persona y que se pueda repetir y auditar el trabajo.",
    whatToDoIfDetected: "Se gestiona desde Documentación (Fase 12); si detectás un documento desactualizado, avisá a Calidad.",
    relatedIds: ["procedimiento", "evidencia"],
  },
  {
    id: "mejora-continua",
    term: "Mejora continua",
    category: "mejora-continua",
    technicalDefinition: "Actividad recurrente orientada a mejorar el desempeño de procesos, productos, servicios o del Sistema de Gestión.",
    simpleDefinition: "Nunca dar un proceso por \"terminado\": siempre buscar una versión mejor.",
    avenidaExample:
      "Cada trimestre, Calidad revisa las NC y OM más frecuentes por área para decidir en qué proceso conviene invertir esfuerzo de mejora.",
    whyItMatters: "Es el motor que evita que el SGC se vuelva un trámite estático en lugar de una forma real de trabajar.",
    whatToDoIfDetected: "Cualquier idea de mejora se puede reportar como Oportunidad de Mejora o Sugerencia.",
    relatedIds: ["oportunidad-de-mejora", "sugerencia"],
  },
  {
    id: "objetivo-de-calidad",
    term: "Objetivo de Calidad",
    category: "planificacion",
    technicalDefinition: "Meta medible que la organización se propone alcanzar en relación con la calidad, coherente con la política de calidad.",
    simpleDefinition: "Una meta concreta y medible, no una intención vaga.",
    avenidaExample: "\"Reducir a menos de 5 días el tiempo promedio de onboarding de un nuevo seller para fin de año.\"",
    whyItMatters: "Sin objetivos medibles, \"mejorar la calidad\" es una frase sin forma de saber si se logró.",
    whatToDoIfDetected: "Se definen en Planificación, con indicador, responsable y frecuencia de seguimiento asociados.",
    relatedIds: ["indicador", "objetivo", "meta"],
  },
  {
    id: "oportunidad",
    term: "Oportunidad",
    category: "riesgos-y-oportunidades",
    technicalDefinition: "Circunstancia o condición que puede permitir obtener una mejora o un resultado favorable.",
    simpleDefinition: "Lo contrario de un riesgo: algo bueno que podría pasar si se lo persigue.",
    avenidaExample: "La posibilidad de integrar un nuevo método de pago que varios sellers vienen pidiendo puede abrir una línea de ingresos nueva.",
    whyItMatters:
      "El SGC no es solo prevenir problemas: también sirve para identificar y capitalizar mejoras estratégicas de forma ordenada.",
    whatToDoIfDetected: "Registrala en Planificación → Riesgos y oportunidades.",
    relatedIds: ["riesgo", "oportunidad-de-mejora"],
  },
  {
    id: "oportunidad-de-mejora",
    term: "Oportunidad de Mejora",
    acronym: "OM",
    category: "mejora-continua",
    technicalDefinition:
      "Propuesta concreta para hacer un proceso más simple, rápido o eficiente, sin que exista necesariamente una No Conformidad detrás.",
    simpleDefinition: "Una idea concreta de \"esto se podría hacer mejor\", con una propuesta, no solo una queja.",
    avenidaExample:
      "Automatizar el envío del comprobante de conciliación a los bancos en vez de armarlo manualmente cada semana.",
    whyItMatters: "Convierte ideas sueltas del día a día en mejoras evaluadas y con seguimiento real.",
    whatToDoIfDetected: "Reportala desde \"Tengo una idea para mejorar algo\" en Reportar.",
    relatedIds: ["mejora-continua", "sugerencia"],
  },
  {
    id: "parte-interesada",
    term: "Parte interesada",
    category: "planificacion",
    technicalDefinition: "Persona u organización que puede afectar, verse afectada, o percibirse afectada por una decisión o actividad de la organización.",
    simpleDefinition: "Cualquiera con quien Avenida+ tenga que ver y a quien le importe cómo nos va.",
    avenidaExample: "Bancos, sellers, colaboradores, proveedores tecnológicos, organismos regulatorios y la propia Dirección son partes interesadas.",
    whyItMatters: "Entender sus necesidades y expectativas evita sorpresas y ayuda a priorizar bien.",
    whatToDoIfDetected: "Se gestionan en Planificación → Partes interesadas.",
    relatedIds: ["contexto-de-la-organizacion", "satisfaccion-del-cliente"],
  },
  {
    id: "politica-de-calidad",
    term: "Política de Calidad",
    category: "liderazgo",
    technicalDefinition: "Declaración formal de la Dirección sobre el compromiso y la orientación de la organización respecto a la calidad.",
    simpleDefinition: "El \"para qué\" de todo el SGC, dicho por la Dirección.",
    avenidaExample:
      "\"En Avenida+ nos comprometemos a que cada integración con bancos y sellers sea confiable, trazable y mejore de forma continua.\"",
    whyItMatters: "Le da sentido y dirección a todos los objetivos, procesos e indicadores del SGC.",
    whatToDoIfDetected: "Se consulta en Documentación; su definición y actualización es responsabilidad de la Dirección.",
    relatedIds: ["objetivo-de-calidad", "revision-por-la-direccion"],
  },
  {
    id: "procedimiento",
    term: "Procedimiento",
    category: "informacion-documentada",
    technicalDefinition: "Forma especificada de llevar a cabo una actividad o un proceso.",
    simpleDefinition: "El \"cómo se hace\", por escrito, para que no dependa de la memoria de una sola persona.",
    avenidaExample: "El procedimiento de activación de un nuevo seller: qué documentación pedir, quién valida, en qué orden.",
    whyItMatters: "Asegura consistencia: que la tarea se haga igual sin importar quién la ejecute.",
    whatToDoIfDetected: "Si un procedimiento no está claro o no se cumple, reportalo como No Conformidad u Oportunidad de Mejora.",
    relatedIds: ["proceso", "informacion-documentada"],
  },
  {
    id: "proceso",
    term: "Proceso",
    category: "procesos",
    technicalDefinition: "Conjunto de actividades relacionadas que utilizan entradas para generar un resultado previsto.",
    simpleDefinition: "Una cadena de pasos que convierte algo (una solicitud, un dato) en un resultado (un servicio, un producto).",
    avenidaExample: "\"Implementación e Integración con Clientes\": entra un contrato firmado, salen una cuenta configurada y una integración funcionando.",
    whyItMatters: "Pensar en procesos (y no en tareas sueltas) permite ver dónde está el cuello de botella real.",
    whatToDoIfDetected: "Consultá el Mapa de procesos para entender cómo se organiza el trabajo en Avenida+.",
    relatedIds: ["procedimiento", "control-operacional"],
  },
  {
    id: "reclamo",
    term: "Reclamo",
    acronym: "R",
    category: "clientes",
    technicalDefinition: "Solicitud formal de resolución ante un incumplimiment de un requisito acordado con un cliente o parte interesada.",
    simpleDefinition: "Un pedido formal de que se resuelva algo que se prometió y no se cumplió.",
    avenidaExample: "Un banco reclama formalmente porque la conciliación diaria acordada por contrato llegó con tres días de atraso durante dos semanas seguidas.",
    whyItMatters: "Un reclamo no atendido a tiempo puede escalar y afectar la relación comercial, no solo la operación.",
    whatToDoIfDetected: "Reportalo desde \"Quiero realizar un reclamo\"; se le asigna fecha compromiso de respuesta.",
    relatedIds: ["queja", "sla", "no-conformidad"],
  },
  {
    id: "queja",
    term: "Queja",
    acronym: "Q",
    category: "clientes",
    technicalDefinition: "Manifestación de insatisfacción respecto de un producto, servicio o proceso, sin que necesariamente exista un incumplimiento contractual formal.",
    simpleDefinition: "Alguien no quedó conforme y lo dice, aunque no haya un contrato de por medio.",
    avenidaExample: "Un seller se queja porque el panel de liquidaciones es confuso y no encuentra dónde ver el detalle de una comisión.",
    whyItMatters: "Las quejas son una fuente temprana de mejora: suelen anticipar problemas antes de que se conviertan en reclamos formales.",
    whatToDoIfDetected: "Reportala desde \"Quiero realizar una queja\"; puede vincularse a una NC o AC si corresponde.",
    relatedIds: ["reclamo", "satisfaccion-del-cliente"],
  },
  {
    id: "requisito",
    term: "Requisito",
    category: "conceptos-de-calidad",
    technicalDefinition: "Necesidad o expectativa establecida que debe cumplirse.",
    simpleDefinition: "Algo que tiene que cumplirse sí o sí: por contrato, por norma, o porque el cliente lo espera.",
    avenidaExample: "El requisito de encriptar los datos bancarios de un seller en tránsito y en reposo.",
    whyItMatters: "Toda No Conformidad parte de un requisito incumplido; sin requisitos claros no se puede evaluar si algo \"está mal\".",
    whatToDoIfDetected: "Si un requisito no está claro o no se está cumpliendo, consultá con tu líder de proceso o reportalo.",
    relatedIds: ["no-conformidad"],
  },
  {
    id: "riesgo",
    term: "Riesgo",
    category: "riesgos-y-oportunidades",
    technicalDefinition: "Efecto de la incertidumbre sobre un resultado u objetivo esperado.",
    simpleDefinition: "Algo malo que todavía no pasó, pero que podría pasar.",
    avenidaExample: "Depender de un único proveedor de infraestructura cloud para toda la plataforma SaaS.",
    whyItMatters: "Identificar riesgos a tiempo permite actuar antes de que se conviertan en una No Conformidad real.",
    whatToDoIfDetected: "Reportalo desde \"Detecté algo que podría generar un problema\" o directamente en Riesgos y oportunidades.",
    relatedIds: ["oportunidad", "accion-preventiva", "contexto-de-la-organizacion"],
  },
  {
    id: "sgc",
    term: "SGC (Sistema de Gestión de Calidad)",
    acronym: "SGC",
    category: "conceptos-de-calidad",
    technicalDefinition:
      "Conjunto de procesos, políticas, roles y registros que una organización usa para dirigir y controlar sus actividades relacionadas con la calidad.",
    simpleDefinition: "La forma organizada en que Avenida+ trabaja, registra, controla y mejora lo que hace — no un área aparte.",
    avenidaExample: "Ágora es la herramienta que centraliza el SGC: desde reportar algo hasta ver riesgos, procesos y objetivos.",
    whyItMatters: "Un SGC bien usado evita reinventar la rueda cada vez que algo sale mal y deja trazabilidad de las decisiones.",
    whatToDoIfDetected: "Participar del SGC no es tarea exclusiva de Calidad: cualquier colaborador puede y debe hacerlo.",
    relatedIds: ["mejora-continua", "trazabilidad"],
  },
  {
    id: "sla",
    term: "SLA (Acuerdo de Nivel de Servicio)",
    acronym: "SLA",
    category: "clientes",
    technicalDefinition: "Compromiso formal sobre el nivel de servicio esperado, generalmente medido en tiempos de respuesta o resolución.",
    simpleDefinition: "El tiempo o nivel de servicio que prometiste cumplir, por escrito.",
    avenidaExample: "\"Los tickets de soporte B2B de prioridad alta se responden dentro de las 4 horas hábiles.\"",
    whyItMatters: "Incumplir un SLA de forma sistemática es una fuente frecuente de No Conformidades y reclamos.",
    whatToDoIfDetected: "Si un SLA se incumple, reportalo para que quede registrado y se pueda analizar el patrón.",
    relatedIds: ["reclamo", "indicador"],
  },
  {
    id: "sugerencia",
    term: "Sugerencia",
    acronym: "S",
    category: "mejora-continua",
    technicalDefinition: "Propuesta o recomendación de cualquier colaborador, evaluada por el área correspondiente para su posible implementación.",
    simpleDefinition: "Una idea que compartís, sin necesidad de tener el análisis completo hecho.",
    avenidaExample: "\"¿Y si agregamos un buscador dentro del panel de liquidaciones de sellers?\"",
    whyItMatters: "Las mejores mejoras muchas veces vienen de quien usa el proceso todos los días, no solo de Calidad.",
    whatToDoIfDetected: "Reportala desde \"Quiero realizar una sugerencia\"; se hace seguimiento hasta que se evalúa.",
    relatedIds: ["oportunidad-de-mejora"],
  },
  {
    id: "trazabilidad",
    term: "Trazabilidad",
    category: "conceptos-de-calidad",
    technicalDefinition:
      "Capacidad de reconstruir y relacionar el origen, evolución, decisiones, actividades, resultados, cambios y evidencias asociadas a un proceso, producto o servicio.",
    simpleDefinition: "Poder reconstruir qué pasó, quién lo hizo y cuándo, mirando el historial.",
    avenidaExample: "Poder ver, para una NC, quién la reportó, cuándo se corrigió, quién definió la Acción Correctiva y cuándo se verificó su eficacia.",
    whyItMatters: "Sin trazabilidad no se puede auditar el SGC ni aprender de forma confiable de lo que pasó.",
    whatToDoIfDetected: "Se genera automáticamente: cada cambio importante en un registro queda en su historial (timeline).",
    relatedIds: ["evidencia", "sgc"],
  },
  {
    id: "verificacion",
    term: "Verificación",
    category: "auditorias",
    technicalDefinition: "Confirmación, mediante la aportación de evidencia objetiva, de que se han cumplido los requisitos especificados.",
    simpleDefinition: "Chequear con pruebas concretas que algo realmente se cumplió, no solo confiar en que se hizo.",
    avenidaExample: "Verificar, con capturas del sistema, que el nuevo control de validación de sellers efectivamente se está aplicando en cada alta.",
    whyItMatters: "Da certeza objetiva en lugar de depender de la palabra de alguien.",
    whatToDoIfDetected: "Se aplica en auditorías y en el cierre de acciones correctivas.",
    relatedIds: ["verificacion-de-eficacia", "evidencia", "auditoria", "validacion"],
  },
  {
    id: "verificacion-de-eficacia",
    term: "Verificación de eficacia",
    category: "mejora-continua",
    technicalDefinition:
      "Confirmación, en un momento posterior a su implementación, de que una Acción Correctiva efectivamente eliminó la causa raíz y evitó la recurrencia.",
    simpleDefinition: "Volver a mirar, un tiempo después, si la solución realmente funcionó.",
    avenidaExample: "Tres meses después de implementar el nuevo control de validación, se revisa si bajaron las NC de sellers con documentación incompleta.",
    whyItMatters: "Sin esta verificación, una Acción Correctiva podría cerrarse \"en el papel\" sin haber resuelto nada en la práctica.",
    whatToDoIfDetected: "Se programa al crear la Acción Correctiva, con fecha y responsable definidos.",
    relatedIds: ["accion-correctiva", "eficacia"],
  },
  {
    id: "contexto-de-la-organizacion",
    term: "Contexto de la organización",
    category: "planificacion",
    technicalDefinition: "Combinación de cuestiones internas y externas que pueden afectar la capacidad de la organización de lograr los resultados esperados de su SGC.",
    simpleDefinition: "Todo lo que pasa adentro y afuera de Avenida+ que puede influir en cómo trabajamos.",
    avenidaExample: "Un cambio regulatorio en medios de pago (externo) o una reestructuración del equipo de Producto (interno) forman parte del contexto.",
    whyItMatters: "Planificar sin mirar el contexto lleva a objetivos y riesgos desconectados de la realidad del negocio.",
    whatToDoIfDetected: "Se documenta y revisa en Planificación → Contexto, incluyendo un análisis FODA/CAME.",
    relatedIds: ["parte-interesada", "riesgo", "cambio"],
  },
  {
    id: "competencia",
    term: "Competencia",
    category: "liderazgo",
    technicalDefinition: "Capacidad de aplicar conocimientos y habilidades para lograr los resultados previstos en un rol.",
    simpleDefinition: "Saber hacer lo que tu rol necesita, no solo tener el cargo.",
    avenidaExample: "Que quien tipifica tickets de Plane sepa distinguir con criterio entre una NC y una Oportunidad de Mejora.",
    whyItMatters: "Un SGC bien diseñado falla igual si las personas que lo ejecutan no tienen la competencia necesaria.",
    whatToDoIfDetected: "Se aborda con capacitación e instructivos; consultá el Centro de Conocimiento para reforzarla.",
    relatedIds: ["toma-de-conciencia"],
  },
  {
    id: "toma-de-conciencia",
    term: "Toma de conciencia",
    category: "liderazgo",
    technicalDefinition: "Grado en el que las personas entienden la política de calidad, los objetivos relevantes y cómo su trabajo contribuye a ellos.",
    simpleDefinition: "Entender por qué lo que hacés todos los días importa para la calidad general.",
    avenidaExample: "Que un desarrollador entienda que un bug mal priorizado puede convertirse en una No Conformidad para un cliente bancario.",
    whyItMatters: "Sin esto, el SGC se percibe como \"cosa de Calidad\" en vez de una responsabilidad de todos.",
    whatToDoIfDetected: "Se refuerza con contenido como \"Calidad en 2 minutos\" y ejemplos concretos del día a día.",
    relatedIds: ["sgc", "competencia"],
  },
  {
    id: "satisfaccion-del-cliente",
    term: "Satisfacción del cliente",
    category: "clientes",
    technicalDefinition: "Percepción del cliente sobre el grado en que se cumplieron sus expectativas.",
    simpleDefinition: "Qué tan conforme está el cliente con lo que le dimos, según su propia percepción.",
    avenidaExample: "Una encuesta trimestral a bancos y sellers integrados sobre la calidad del soporte y la estabilidad de la plataforma.",
    whyItMatters: "Es uno de los mejores termómetros de si el SGC está funcionando de verdad, más allá de los procesos internos.",
    whatToDoIfDetected: "Se hace seguimiento en Evaluación → Satisfacción, vinculado a quejas y reclamos.",
    relatedIds: ["queja", "reclamo"],
  },
  {
    id: "proveedor-externo",
    term: "Proveedor externo",
    category: "proveedores",
    technicalDefinition: "Organización externa que provee un producto o servicio que la organización utiliza o incorpora en lo que ofrece.",
    simpleDefinition: "Alguien de afuera de quien dependemos para poder operar.",
    avenidaExample: "El proveedor de infraestructura cloud, el proveedor de firma digital de contratos, o el partner de conciliación bancaria.",
    whyItMatters: "Un problema de un proveedor externo se convierte rápido en un problema propio si no se gestiona el riesgo asociado.",
    whatToDoIfDetected: "Se gestionan en Configuración → Proveedores, con criticidad, SLA y evaluación asociada.",
    relatedIds: ["riesgo", "sla"],
  },
  {
    id: "desempeno",
    term: "Desempeño",
    category: "indicadores",
    technicalDefinition: "Resultado medible de una actividad, proceso, producto o sistema, comparado contra lo esperado.",
    simpleDefinition: "Qué tan bien está funcionando algo, en números.",
    avenidaExample: "El desempeño del proceso de onboarding de sellers medido en tiempo promedio y tasa de errores.",
    whyItMatters: "Permite comparar objetivamente contra el pasado o contra la meta, no solo \"sentir\" que algo mejoró.",
    whatToDoIfDetected: "Se revisa a través de los indicadores definidos por proceso.",
    relatedIds: ["indicador", "medicion"],
  },
  {
    id: "seguimiento",
    term: "Seguimiento",
    category: "indicadores",
    technicalDefinition: "Determinación del estado de un sistema, proceso o actividad, de forma repetida a lo largo del tiempo.",
    simpleDefinition: "Mirar cómo evoluciona algo, no solo una vez, sino de forma continua.",
    avenidaExample: "El seguimiento mensual de cuántas NC quedaron abiertas más allá de su fecha compromiso.",
    whyItMatters: "Sin seguimiento, un problema resuelto \"una vez\" puede reaparecer sin que nadie lo note a tiempo.",
    whatToDoIfDetected: "Se centraliza en Evaluación → Seguimiento, con foco en vencimientos y reincidencias.",
    relatedIds: ["indicador", "desempeno"],
  },
  {
    id: "medicion",
    term: "Medición",
    category: "indicadores",
    technicalDefinition: "Proceso para determinar un valor, generalmente a través de un instrumento o método definido.",
    simpleDefinition: "La forma concreta de obtener el número de un indicador.",
    avenidaExample: "Medir el tiempo de respuesta de soporte tomando la diferencia entre la apertura y la primera respuesta de cada ticket.",
    whyItMatters: "Un indicador mal medido lleva a decisiones basadas en datos poco confiables.",
    whatToDoIfDetected: "Se define junto con cada indicador: fuente, fórmula y frecuencia.",
    relatedIds: ["indicador", "desempeno"],
  },
  {
    id: "auditoria",
    term: "Auditoría",
    category: "auditorias",
    technicalDefinition: "Proceso sistemático de obtención y evaluación de evidencias para determinar el grado de cumplimiento de los criterios establecidos.",
    simpleDefinition: "Una revisión ordenada y objetiva de cómo se está trabajando realmente.",
    avenidaExample: "Una auditoría al proceso de Gestión de Proveedores y Terceros para revisar si se está cumpliendo el procedimiento de evaluación anual.",
    whyItMatters: "Es la forma más estructurada de confirmar (o desmentir) que el SGC funciona como se describe.",
    whatToDoIfDetected: "El calendario y los hallazgos de auditorías se gestionan en Evaluación → Auditorías.",
    relatedIds: ["auditoria-interna", "hallazgo", "verificacion"],
  },
  {
    id: "auditoria-interna",
    term: "Auditoría interna",
    category: "auditorias",
    technicalDefinition: "Auditoría realizada por la propia organización (o en su nombre) para evaluar su SGC, generalmente en preparación de una certificación o revisión.",
    simpleDefinition: "Cuando Avenida+ se audita a sí misma, antes de que lo haga alguien de afuera.",
    avenidaExample: "El equipo de Calidad audita el proceso de Soporte y Atención al Cliente B2B una vez al año.",
    whyItMatters: "Detecta problemas antes de que los encuentre un cliente, un banco regulado o un auditor externo.",
    whatToDoIfDetected: "Se programa desde Evaluación → Auditorías, con alcance y criterios definidos de antemano.",
    relatedIds: ["auditoria", "revision-por-la-direccion"],
  },
  {
    id: "revision-por-la-direccion",
    term: "Revisión por la dirección",
    category: "liderazgo",
    technicalDefinition: "Evaluación periódica que hace la Dirección sobre el desempeño y la adecuación del SGC, para decidir ajustes u oportunidades de mejora.",
    simpleDefinition: "El momento en que la Dirección mira los resultados del SGC completo y decide qué cambiar.",
    avenidaExample:
      "Una vez al año, Dirección revisa indicadores, auditorías, riesgos y objetivos de todo el SGC para decidir prioridades del próximo período.",
    whyItMatters: "Sin esta revisión, el SGC puede quedar desconectado de las decisiones estratégicas del negocio.",
    whatToDoIfDetected: "Es responsabilidad de la Dirección, con insumos que aporta el Dashboard Ejecutivo (Fase 14).",
    relatedIds: ["politica-de-calidad", "objetivo-de-calidad"],
  },
  {
    id: "control-operacional",
    term: "Control operacional",
    category: "procesos",
    technicalDefinition: "Medidas y condiciones que se establecen para asegurar que un proceso se ejecute según lo planificado.",
    simpleDefinition: "Las barreras o chequeos que evitan que un proceso se salga de control.",
    avenidaExample: "Un control automático que impide activar a un seller en el marketplace si falta algún documento obligatorio.",
    whyItMatters: "Reduce la dependencia de que una persona \"se acuerde\" de hacer algo bien cada vez.",
    whatToDoIfDetected: "Se define y documenta como parte de la ficha de cada proceso.",
    relatedIds: ["proceso", "riesgo"],
  },
  {
    id: "cambio",
    term: "Cambio",
    category: "planificacion",
    technicalDefinition: "Modificación planificada o no planificada en el contexto, los procesos o el SGC que puede requerir evaluación de su impacto.",
    simpleDefinition: "Algo que se modifica y que puede afectar cómo trabajamos.",
    avenidaExample: "La incorporación de un nuevo método de pago o un cambio regulatorio sobre datos bancarios.",
    whyItMatters: "Un cambio no evaluado puede introducir riesgos nuevos sin que nadie los haya considerado.",
    whatToDoIfDetected: "Se evalúa como parte del Contexto de la organización y, si aplica, genera nuevos riesgos u objetivos.",
    relatedIds: ["contexto-de-la-organizacion", "riesgo"],
  },
  {
    id: "objetivo",
    term: "Objetivo",
    category: "planificacion",
    technicalDefinition: "Resultado a lograr, que puede ser estratégico, táctico u operativo, y no necesariamente medido en términos de calidad.",
    simpleDefinition: "Un resultado que se busca lograr, en general.",
    avenidaExample: "\"Expandir la integración con dos bancos nuevos este año\" es un objetivo de negocio; cuando se mide y vincula a calidad, se vuelve un Objetivo de Calidad.",
    whyItMatters: "Da dirección al trabajo de un área o de la organización completa.",
    whatToDoIfDetected: "Se distingue de la Meta (el valor puntual a alcanzar) y del Objetivo de Calidad (su versión medible dentro del SGC).",
    relatedIds: ["objetivo-de-calidad", "meta"],
  },
  {
    id: "meta",
    term: "Meta",
    category: "planificacion",
    technicalDefinition: "Valor específico que se busca alcanzar para un objetivo, generalmente con un plazo definido.",
    simpleDefinition: "El número o valor puntual que hay que llegar a cumplir.",
    avenidaExample: "Para el objetivo \"reducir el tiempo de onboarding\", la meta puede ser \"5 días o menos para el 31 de diciembre\".",
    whyItMatters: "Sin una meta concreta, un objetivo queda abierto a interpretación sobre cuándo se considera cumplido.",
    whatToDoIfDetected: "Se define junto con cada Objetivo de Calidad y su indicador asociado.",
    relatedIds: ["objetivo", "objetivo-de-calidad"],
  },

  // ---------------------------------------------------------------------
  // A partir de acá: términos incorporados del Diccionario Corporativo de
  // Términos del Sistema de Gestión (v0, 27/08/2026) que todavía no
  // existían en el Centro de Conocimiento.
  // ---------------------------------------------------------------------
  {
    id: "analisis-de-causa",
    term: "Análisis de causa",
    category: "mejora-continua",
    technicalDefinition: "Actividad destinada a identificar y analizar las causas que originaron o contribuyeron a una No Conformidad o problema.",
    simpleDefinition: "Investigar en serio por qué pasó algo, antes de decidir qué hacer al respecto.",
    avenidaExample: "Ante pases a producción sin aprobación obligatoria, primero se determina por qué el proceso lo permitió, antes de definir la Acción Correctiva.",
    whyItMatters: "Permite determinar por qué ocurrió una situación, para definir acciones que realmente eviten su recurrencia.",
    whatToDoIfDetected: "Se hace al gestionar una No Conformidad, antes de cargar la Acción Correctiva.",
    relatedIds: ["causa-raiz", "causa", "accion-correctiva", "no-conformidad"],
  },
  {
    id: "aprobacion",
    term: "Aprobación",
    category: "procesos",
    technicalDefinition:
      "Confirmación formal mediante la cual una persona o rol con autoridad acepta un resultado, documento, actividad o entregable y habilita su continuidad dentro del proceso.",
    simpleDefinition: "El OK formal de alguien con autoridad para que algo pueda seguir adelante.",
    avenidaExample: "Aprobación de una especificación funcional antes de iniciar el desarrollo.",
    whyItMatters: "Sin una aprobación clara, cualquiera podría avanzar una etapa sin que nadie confirme que está lista.",
    whatToDoIfDetected: "Si algo avanzó sin la aprobación que el proceso exige, es una No Conformidad.",
    relatedIds: ["aprobador", "control-de-cambios", "no-conformidad"],
  },
  {
    id: "aprobador",
    term: "Aprobador",
    category: "procesos",
    technicalDefinition: "Persona o rol que posee la autoridad definida para aceptar formalmente un resultado, documento, actividad o entregable.",
    simpleDefinition: "Quien tiene la autoridad definida para dar el OK.",
    avenidaExample: "El Product Owner suele ser el aprobador de una especificación funcional antes de que empiece el desarrollo.",
    whyItMatters: "Si no está claro quién aprueba, tampoco queda claro quién es responsable si algo pasa igual sin estar listo.",
    whatToDoIfDetected: "Se define en el procedimiento de cada proceso, no se asume caso por caso.",
    relatedIds: ["aprobacion", "responsable"],
  },
  {
    id: "auditor",
    term: "Auditor",
    category: "auditorias",
    technicalDefinition: "Persona que lleva adelante una auditoría y evalúa las evidencias disponibles respecto de los criterios establecidos.",
    simpleDefinition: "Quien revisa, con evidencia, si se está cumpliendo lo que se definió.",
    avenidaExample: "Alguien de Calidad (o entrenado por Calidad) que revisa registros y procedimientos de un proceso puntual.",
    whyItMatters: "Un auditor evalúa con criterios objetivos, no con impresiones — eso le da valor a la auditoría.",
    whatToDoIfDetected: "Se define en Evaluación → Auditorías al planificar cada auditoría.",
    relatedIds: ["auditoria", "criterio-de-auditoria", "hallazgo"],
  },
  {
    id: "cambio-de-diseno-y-desarrollo",
    term: "Cambio de Diseño y Desarrollo",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Modificación realizada sobre requisitos, entradas, definiciones, diseños o resultados del proceso de Diseño y Desarrollo.",
    simpleDefinition: "Cuando algo de lo ya definido para una solución cambia en el medio del camino.",
    avenidaExample: "Cambio de una regla de negocio una vez iniciado el desarrollo.",
    whyItMatters:
      "Los cambios deben identificarse, revisarse, evaluarse en su impacto y autorizarse antes de implementarse, manteniendo los registros aplicables — si no, se pierde trazabilidad de por qué la solución terminó siendo distinta a lo planificado.",
    whatToDoIfDetected: "Documentalo y hacé que se revise el impacto antes de aplicarlo, no después.",
    relatedIds: ["diseno-y-desarrollo", "control-de-cambios", "requisito"],
  },
  {
    id: "causa",
    term: "Causa",
    category: "mejora-continua",
    technicalDefinition: "Motivo o condición que originó o contribuyó a que ocurriera una situación, problema o No Conformidad.",
    simpleDefinition: "Algo que contribuyó a que pasara lo que pasó — no necesariamente la de fondo.",
    avenidaExample: "Que un ambiente de testing no reflejara los datos de producción fue una de las causas de que un bug no se detectara antes.",
    whyItMatters: "Distinguir causa de causa raíz evita quedarse en la primera explicación que aparece.",
    whatToDoIfDetected: "Se identifica durante el análisis de causa de una No Conformidad.",
    relatedIds: ["causa-raiz", "analisis-de-causa"],
  },
  {
    id: "contencion",
    term: "Contención",
    category: "mejora-continua",
    technicalDefinition: "Acción inmediata destinada a controlar, limitar o reducir las consecuencias de un problema mientras se analiza y determina su tratamiento definitivo.",
    simpleDefinition: "Frenar el daño ahora, aunque todavía no se haya resuelto el problema de fondo.",
    avenidaExample: "Deshabilitar temporalmente una funcionalidad que presenta un comportamiento incorrecto.",
    whyItMatters: "Contención y Corrección pueden parecer lo mismo pero no lo son — la contención busca controlar el impacto, la corrección busca eliminar la No Conformidad; a veces hacen falta las dos.",
    whatToDoIfDetected: "Aplicala apenas detectás el problema, sin esperar el análisis completo.",
    relatedIds: ["correccion", "no-conformidad"],
  },
  {
    id: "control",
    term: "Control",
    category: "procesos",
    technicalDefinition: "Actividad destinada a comprobar o asegurar que una condición, actividad o resultado cumple con los requisitos o criterios definidos.",
    simpleDefinition: "Un chequeo puesto a propósito para asegurar que algo salga bien.",
    avenidaExample: "Un control automático que impide activar a un seller si falta un documento obligatorio.",
    whyItMatters: "Reduce la dependencia de que alguien se acuerde de hacer bien las cosas cada vez.",
    whatToDoIfDetected: "Se documenta como parte del procedimiento o la ficha del proceso correspondiente.",
    relatedIds: ["control-operacional", "control-de-cambios"],
  },
  {
    id: "control-de-cambios",
    term: "Control de cambios",
    category: "procesos",
    technicalDefinition: "Proceso mediante el cual los cambios son identificados, analizados, registrados, revisados y autorizados de acuerdo con los criterios definidos antes de su implementación.",
    simpleDefinition: "El proceso ordenado para que un cambio no se aplique sin que alguien lo haya evaluado antes.",
    avenidaExample: "Antes de modificar una regla de negocio ya en producción, se registra el cambio, se evalúa su impacto y se autoriza.",
    whyItMatters: "Sin control de cambios, un cambio no evaluado puede introducir riesgos que nadie consideró.",
    whatToDoIfDetected: "Se aplica a cualquier cambio sobre procesos, sistemas o el propio SGC.",
    relatedIds: ["cambio", "cambio-de-diseno-y-desarrollo", "control"],
  },
  {
    id: "criterio-de-aceptacion",
    term: "Criterio de aceptación",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Condición objetiva y verificable que debe cumplirse para considerar aceptable un resultado, producto, servicio o funcionalidad.",
    simpleDefinition: "Las condiciones concretas que hay que cumplir para decir \"esto está bien hecho\".",
    avenidaExample: "Definir las condiciones que deberá cumplir una funcionalidad para considerarse correctamente implementada.",
    whyItMatters: "Sin criterios claros, \"terminado\" queda a criterio de cada persona.",
    whatToDoIfDetected: "Se define al planificar el Diseño y Desarrollo de una solución, no después de construirla.",
    relatedIds: ["especificacion-funcional", "validacion", "verificacion"],
  },
  {
    id: "criterio-de-auditoria",
    term: "Criterio de auditoría",
    category: "auditorias",
    technicalDefinition: "Requisito, política, procedimiento, norma u otra referencia utilizada para comparar y evaluar las evidencias durante una auditoría.",
    simpleDefinition: "Contra qué se compara lo que encuentra el auditor.",
    avenidaExample: "El procedimiento de evaluación anual de proveedores es el criterio de auditoría al revisar si se cumplió ese proceso.",
    whyItMatters: "Sin un criterio explícito, un hallazgo se vuelve una opinión en vez de una comprobación objetiva.",
    whatToDoIfDetected: "Se define al planificar cada auditoría, junto con su alcance.",
    relatedIds: ["auditoria", "auditor", "hallazgo"],
  },
  {
    id: "defecto-bug",
    term: "Defecto / Bug",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Error presente en un producto de software que provoca un comportamiento diferente del esperado o especificado.",
    simpleDefinition: "Algo en el software que no funciona como debería.",
    avenidaExample: "Un cálculo de comisión que da un resultado distinto al definido en la especificación funcional.",
    whyItMatters: "Un bug que llega a producción sin control puede convertirse en una No Conformidad si viola un requisito documentado.",
    whatToDoIfDetected: "Reportalo por el canal técnico correspondiente (ticket); si afecta un requisito comprometido con un cliente, puede además registrarse como NC.",
    relatedIds: ["requisito-funcional", "retrabajo", "no-conformidad"],
  },
  {
    id: "deploy",
    term: "Deploy / Pase a Producción",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Actividad mediante la cual una versión aprobada de una solución es implementada en el ambiente productivo.",
    simpleDefinition: "El momento en que algo pasa de \"probado\" a \"ya está andando para todos\".",
    avenidaExample: "Pasar a producción una nueva funcionalidad del panel de liquidaciones ya validada.",
    whyItMatters: "Un deploy sin las aprobaciones correspondientes es, en sí mismo, una fuente típica de No Conformidad.",
    whatToDoIfDetected: "Verificá que estén las aprobaciones y evidencias que el proceso exige antes de pasar a producción.",
    relatedIds: ["aprobacion", "validacion", "uat"],
  },
  {
    id: "desarrollo",
    term: "Desarrollo",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Actividad mediante la cual se implementan técnicamente los requisitos y diseños definidos para una solución.",
    simpleDefinition: "Programar y construir lo que el diseño definió.",
    avenidaExample: "Codificar la funcionalidad de conciliación bancaria según el diseño técnico aprobado.",
    whyItMatters: "Si el desarrollo se aparta del diseño y los requisitos sin registrarlo, se pierde trazabilidad.",
    whatToDoIfDetected: "Cualquier ajuste respecto del diseño original debería tratarse como un Cambio de Diseño y Desarrollo.",
    relatedIds: ["diseno-y-desarrollo", "diseno-tecnico", "cambio-de-diseno-y-desarrollo"],
  },
  {
    id: "desvio",
    term: "Desvío",
    category: "conceptos-de-calidad",
    technicalDefinition: "Diferencia identificada entre una condición definida o esperada y lo que efectivamente ocurrió.",
    simpleDefinition: "Algo salió distinto a lo esperado — pero eso todavía no dice si está mal.",
    avenidaExample: "Un proceso tardó más de lo estimado en completarse, sin que eso incumpla ningún requisito acordado.",
    whyItMatters: "Un desvío no implica automáticamente una No Conformidad: hay que evaluarlo contra los requisitos aplicables antes de tratarlo como tal.",
    whatToDoIfDetected: "Evaluá si hay un requisito incumplido de por medio; si lo hay, es una No Conformidad, si no, es solo un desvío a observar.",
    relatedIds: ["no-conformidad", "observacion"],
  },
  {
    id: "diseno",
    term: "Diseño",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Actividad mediante la cual los requisitos se transforman progresivamente en definiciones y características de una solución que permitan su posterior desarrollo o implementación.",
    simpleDefinition: "Traducir lo que se necesita en una definición concreta de cómo se va a construir.",
    avenidaExample: "Definir cómo se va a comportar y estructurar una nueva funcionalidad antes de empezar a programarla.",
    whyItMatters: "Sin diseño, el desarrollo arranca sin una definición clara de qué construir.",
    whatToDoIfDetected: "Se planifica como parte de la Planificación de Diseño y Desarrollo.",
    relatedIds: ["diseno-funcional", "diseno-tecnico", "diseno-y-desarrollo"],
  },
  {
    id: "diseno-funcional",
    term: "Diseño funcional",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Definición del comportamiento esperado de una solución desde la perspectiva funcional, del negocio y/o del usuario.",
    simpleDefinition: "Qué tiene que hacer la solución, visto desde el negocio y el usuario.",
    avenidaExample: "Definir cómo debe comportarse el flujo de alta de un seller desde la perspectiva de quien lo usa.",
    whyItMatters: "Sin esto, el desarrollo puede construir algo técnicamente correcto pero que no resuelve la necesidad real.",
    whatToDoIfDetected: "Se documenta habitualmente en la especificación funcional.",
    relatedIds: ["diseno-tecnico", "especificacion-funcional"],
  },
  {
    id: "diseno-tecnico",
    term: "Diseño técnico",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Definición de la solución desde el punto de vista técnico, incluyendo cuando corresponda arquitectura, componentes, integraciones, APIs, estructuras de datos u otras decisiones necesarias para su implementación.",
    simpleDefinition: "Cómo se va a construir por dentro, en términos técnicos.",
    avenidaExample: "Definir la arquitectura y las integraciones necesarias para la conciliación automática con un banco nuevo.",
    whyItMatters: "Decisiones técnicas no evaluadas a tiempo suelen ser más caras de corregir una vez desarrolladas.",
    whatToDoIfDetected: "Se revisa como parte de la Revisión de Diseño y Desarrollo.",
    relatedIds: ["diseno-funcional", "revision-de-diseno-y-desarrollo"],
  },
  {
    id: "diseno-y-desarrollo",
    term: "Diseño y Desarrollo (D&D)",
    acronym: "D&D",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Proceso mediante el cual los requisitos aplicables se transforman progresivamente en características definidas de un producto o servicio, contemplando su planificación, entradas, controles, salidas y cambios.",
    simpleDefinition: "Todo el camino desde \"necesitamos esto\" hasta \"esto ya está construido y andando\".",
    avenidaExample: "Todo el proceso de construir una nueva integración con un banco, desde que se define la necesidad hasta que queda funcionando en producción.",
    whyItMatters: "Gestionarlo como proceso (con entradas, controles y salidas claras) evita que la calidad del resultado dependa solo de la habilidad individual de quien lo construye.",
    whatToDoIfDetected: "Consultá los términos relacionados (Planificación, Elementos de entrada/salida, Revisión, Verificación, Validación) para cada etapa.",
    relatedIds: ["planificacion-de-diseno-y-desarrollo", "elementos-de-entrada-dyd", "elementos-de-salida-dyd", "cambio-de-diseno-y-desarrollo"],
  },
  {
    id: "elementos-de-entrada-dyd",
    term: "Elementos de entrada de Diseño y Desarrollo",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Información y requisitos que deben ser considerados para diseñar y desarrollar un producto o servicio.",
    simpleDefinition: "Todo lo que hay que tener en cuenta antes de diseñar algo, no solo \"lo que pidió el cliente\".",
    avenidaExample:
      "Para una nueva integración: los requisitos funcionales pedidos, requisitos legales del rubro bancario, riesgos identificados y restricciones técnicas conocidas.",
    whyItMatters: "Si faltan entradas relevantes (ej. un requisito legal), el diseño resultante puede quedar incompleto o directamente incumplirlo.",
    whatToDoIfDetected: "Se recopilan al planificar el Diseño y Desarrollo, antes de empezar a diseñar.",
    relatedIds: ["requisito-funcional", "requisito-legal-y-reglamentario", "riesgo", "elementos-de-salida-dyd"],
  },
  {
    id: "elementos-de-salida-dyd",
    term: "Elementos de salida de Diseño y Desarrollo",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Resultados generados por el proceso de Diseño y Desarrollo.",
    simpleDefinition: "Lo que efectivamente sale del proceso — y que tiene que poder rastrearse hasta las entradas que le dieron origen.",
    avenidaExample: "El código funcionando, la documentación técnica y los criterios de aceptación cumplidos de una nueva funcionalidad.",
    whyItMatters: "Las salidas deben poder compararse contra las entradas para confirmar que se cumplió lo que se pidió — de eso se ocupan la Verificación y la Validación.",
    whatToDoIfDetected: "Se revisan al hacer la Verificación y Validación de la solución.",
    relatedIds: ["elementos-de-entrada-dyd", "verificacion", "validacion"],
  },
  {
    id: "especificacion-funcional",
    term: "Especificación funcional",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Documento o registro que describe el alcance, comportamiento, reglas, condiciones y requisitos funcionales esperados de una solución.",
    simpleDefinition: "El documento que describe, en detalle, qué tiene que hacer la solución.",
    avenidaExample: "El documento que detalla cómo debe comportarse el nuevo flujo de liquidaciones antes de que empiece el desarrollo.",
    whyItMatters: "Puede ser una de las entradas clave del Diseño y Desarrollo cuando contiene los requisitos necesarios para orientarlo.",
    whatToDoIfDetected: "Debería estar aprobada antes de iniciar el desarrollo, no redactarse en paralelo.",
    relatedIds: ["diseno-funcional", "requisito-funcional", "aprobacion"],
  },
  {
    id: "evidencia-objetiva",
    term: "Evidencia objetiva",
    category: "informacion-documentada",
    technicalDefinition: "Información verificable que permite demostrar la existencia, realización o veracidad de una actividad, condición o resultado.",
    simpleDefinition: "Una prueba concreta y chequeable, no solo la palabra de alguien.",
    avenidaExample: "Un ticket, un registro de aprobación, el resultado de una prueba, un acta o una planilla generada por una herramienta.",
    whyItMatters:
      "Un registro puede constituir evidencia objetiva, pero no son exactamente lo mismo: la evidencia objetiva puede encontrarse en distintos soportes, no solo en un registro formal.",
    whatToDoIfDetected: "Adjuntala cada vez que reportes o gestiones algo en el portal — capturas, links, archivos.",
    relatedIds: ["evidencia", "registro", "verificacion"],
  },
  {
    id: "incidente",
    term: "Incidente",
    category: "conceptos-de-calidad",
    technicalDefinition: "Evento no planificado que afecta o puede afectar la operación, el producto, el servicio o el cumplimiento de un resultado esperado.",
    simpleDefinition: "Algo inesperado que interrumpe o pone en riesgo que las cosas funcionen como deberían.",
    avenidaExample: "Una caída del servicio de conciliación bancaria durante un horario pico.",
    whyItMatters: "Tratarlo a tiempo evita que un incidente puntual se convierta en un problema recurrente o en una No Conformidad no analizada.",
    whatToDoIfDetected: "Contené el impacto primero, y evaluá después si corresponde registrarlo como No Conformidad.",
    relatedIds: ["contencion", "no-conformidad"],
  },
  {
    id: "instructivo",
    term: "Instructivo",
    category: "informacion-documentada",
    technicalDefinition: "Documento que describe de manera operativa cómo realizar una actividad o conjunto específico de tareas.",
    simpleDefinition: "El paso a paso concreto de cómo hacer algo puntual — no el \"qué se hace\" en general (eso es el procedimiento).",
    avenidaExample: "El instructivo de \"Cómo tipificar un ticket de Plane\".",
    whyItMatters: "Un procedimiento dice qué hacer y quién lo hace; un instructivo baja eso al paso a paso operativo — confundirlos genera documentación poco clara.",
    whatToDoIfDetected: "Se gestiona desde Documentación; si está desactualizado, avisá a Calidad.",
    relatedIds: ["procedimiento", "registro"],
  },
  {
    id: "mejora",
    term: "Mejora",
    category: "mejora-continua",
    technicalDefinition: "Actividad o acción destinada a aumentar la capacidad de un proceso, producto, servicio o sistema para obtener mejores resultados.",
    simpleDefinition: "Hacer que algo funcione mejor de lo que ya funcionaba.",
    avenidaExample: "Simplificar un flujo que ya cumplía los requisitos, para que sea más rápido de ejecutar.",
    whyItMatters: "Una mejora no requiere que antes haya existido una No Conformidad — se puede mejorar algo que ya andaba bien.",
    whatToDoIfDetected: "Reportala como Oportunidad de Mejora o Sugerencia, según qué tan desarrollada esté la idea.",
    relatedIds: ["mejora-continua", "oportunidad-de-mejora", "sugerencia"],
  },
  {
    id: "necesidad",
    term: "Necesidad",
    category: "planificacion",
    technicalDefinition: "Situación, expectativa, problema u oportunidad que puede dar origen a un requisito o iniciativa.",
    simpleDefinition: "Lo que hace falta, antes de que se lo transforme en un requisito formal.",
    avenidaExample: "Los sellers necesitan ver el detalle de sus comisiones — esa necesidad, una vez definida, se convierte en un requisito funcional del panel.",
    whyItMatters: "Si se salta directo al requisito sin entender bien la necesidad de fondo, se puede terminar resolviendo el problema equivocado.",
    whatToDoIfDetected: "Es el punto de partida de la cadena de trazabilidad: Necesidad → Requisito → Diseño → Desarrollo.",
    relatedIds: ["requisito", "trazabilidad"],
  },
  {
    id: "observacion",
    term: "Observación",
    category: "conceptos-de-calidad",
    technicalDefinition: "Situación identificada que merece atención, análisis o seguimiento pero que no necesariamente representa el incumplimiento de un requisito.",
    simpleDefinition: "Algo que vale la pena mirar, aunque todavía no sea un incumplimiento confirmado.",
    avenidaExample: "Un proceso que funciona pero con pasos manuales que podrían fallar si la persona que los hace no está disponible.",
    whyItMatters: "Una Observación no es lo mismo que una No Conformidad — confundirlas hace que se sobre-reaccione o se sub-reaccione ante lo que se encontró.",
    whatToDoIfDetected: "Registrala para seguimiento; si más adelante se confirma un requisito incumplido, ahí sí se convierte en No Conformidad.",
    relatedIds: ["no-conformidad", "hallazgo", "desvio"],
  },
  {
    id: "peer-review",
    term: "Peer Review / Revisión de Código",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Revisión técnica del código realizada para evaluar su adecuación respecto de los criterios técnicos definidos antes de continuar con las etapas posteriores.",
    simpleDefinition: "Que otra persona del equipo técnico revise el código antes de que avance.",
    avenidaExample: "Un desarrollador revisa el Pull Request de otro antes de que se mergee a la rama principal.",
    whyItMatters: "Es un control clave para detectar errores o desvíos técnicos antes de que lleguen a producción.",
    whatToDoIfDetected: "Debería ser un paso obligatorio antes del deploy, no una excepción cuando hay tiempo.",
    relatedIds: ["desarrollo", "control", "deploy"],
  },
  {
    id: "planificacion-de-diseno-y-desarrollo",
    term: "Planificación de Diseño y Desarrollo",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Actividad mediante la cual se determinan las etapas, controles, responsabilidades, recursos, interacciones y registros necesarios para desarrollar adecuadamente un producto o servicio.",
    simpleDefinition: "Definir de antemano cómo se va a llevar adelante todo el proceso de construir algo, no solo lanzarse a hacerlo.",
    avenidaExample: "Definir, antes de empezar, quién revisa, quién verifica, quién valida y qué se necesita para una integración nueva.",
    whyItMatters: "Sin planificación, cada Diseño y Desarrollo se organiza de forma distinta según quién lo lleve adelante.",
    whatToDoIfDetected: "Se define al inicio del proceso de Diseño y Desarrollo de cada solución relevante.",
    relatedIds: ["diseno-y-desarrollo", "revision-de-diseno-y-desarrollo", "responsable"],
  },
  {
    id: "producto",
    term: "Producto",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Solución, plataforma o sistema propio de la organización que evoluciona mediante el desarrollo e incorporación de funcionalidades y que puede ser utilizado por múltiples clientes.",
    simpleDefinition: "La plataforma o sistema propio que va creciendo con nuevas funcionalidades, no un entregable puntual.",
    avenidaExample: "Incorporación de una nueva funcionalidad a un Producto interno que luego podrán usar los clientes que operan con ese Producto.",
    whyItMatters: "No confundir con el Equipo de Producto: acá \"Producto\" es la solución en sí, no el equipo que la define.",
    whatToDoIfDetected: "Las funcionalidades nuevas se incorporan de acuerdo con las condiciones y configuraciones que correspondan a cada cliente.",
    relatedIds: ["equipo-de-producto", "diseno-y-desarrollo"],
  },
  {
    id: "equipo-de-producto",
    term: "Equipo de Producto",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Equipo responsable de participar en la definición, diseño y evolución de los Productos y Tiendas de la organización.",
    simpleDefinition: "El equipo (Product Owner, Product Designer, UX/UI) que define hacia dónde evoluciona cada Producto.",
    avenidaExample: "El Product Owner, el Product Designer y UX/UI definiendo juntos la próxima funcionalidad del panel de liquidaciones.",
    whyItMatters: "Sus responsabilidades específicas se establecen en los procedimientos de cada proceso — no es un rol genérico sin límites definidos.",
    whatToDoIfDetected: "No confundir con \"Producto\" entendido como la solución o plataforma en sí.",
    relatedIds: ["producto", "ux", "ui"],
  },
  {
    id: "registro",
    term: "Registro",
    category: "informacion-documentada",
    technicalDefinition: "Información documentada que proporciona evidencia de actividades realizadas o resultados obtenidos.",
    simpleDefinition: "La constancia de que algo se hizo o de qué resultado se obtuvo.",
    avenidaExample: "Un registro de UAT, un registro de revisión, o una aprobación registrada en una herramienta.",
    whyItMatters: "No confundir con Procedimiento: el procedimiento dice cómo se hace algo, el registro demuestra que efectivamente se hizo.",
    whatToDoIfDetected: "Cada actividad relevante del SGC debería dejar su registro correspondiente.",
    relatedIds: ["evidencia-objetiva", "procedimiento", "informacion-documentada"],
  },
  {
    id: "requisito-de-desempeno",
    term: "Requisito de desempeño",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Condición que establece los niveles o características de desempeño que debe cumplir un producto, servicio o solución.",
    simpleDefinition: "Qué tan bien (rápido, disponible, preciso) tiene que funcionar algo.",
    avenidaExample: "Que la conciliación bancaria automática procese el 100% de los movimientos del día en menos de 10 minutos.",
    whyItMatters: "Sin esto, \"funciona\" no dice nada sobre si funciona lo suficientemente bien para el uso previsto.",
    whatToDoIfDetected: "Se define como parte de los elementos de entrada del Diseño y Desarrollo.",
    relatedIds: ["requisito-funcional", "elementos-de-entrada-dyd"],
  },
  {
    id: "requisito-funcional",
    term: "Requisito funcional",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Condición que establece el comportamiento o funcionalidad que debe cumplir un producto, servicio o solución.",
    simpleDefinition: "Qué tiene que hacer la solución, concretamente.",
    avenidaExample: "El sistema debe permitir a un seller ver el detalle de cada comisión cobrada por período.",
    whyItMatters: "Es contra lo que se verifica si el desarrollo cumplió lo que se pidió.",
    whatToDoIfDetected: "Se documenta habitualmente en la especificación funcional antes del desarrollo.",
    relatedIds: ["especificacion-funcional", "requisito-de-desempeno", "verificacion"],
  },
  {
    id: "requisito-legal-y-reglamentario",
    term: "Requisito legal y reglamentario",
    category: "conceptos-de-calidad",
    technicalDefinition: "Requisito obligatorio proveniente de legislación, regulación u otra disposición aplicable a la organización, producto, servicio o proceso.",
    simpleDefinition: "Lo que hay que cumplir sí o sí porque lo exige una ley o un regulador, no porque lo decidió Avenida+.",
    avenidaExample: "Requisitos de seguridad de datos exigidos por la normativa bancaria aplicable a las integraciones con bancos.",
    whyItMatters: "Incumplir un requisito legal no es solo una No Conformidad interna — puede tener consecuencias regulatorias reales.",
    whatToDoIfDetected: "Se identifica al planificar el Diseño y Desarrollo o el proceso que corresponda, no se descubre después.",
    relatedIds: ["requisito", "elementos-de-entrada-dyd"],
  },
  {
    id: "responsable",
    term: "Responsable",
    category: "liderazgo",
    technicalDefinition: "Persona o rol al que se asigna la responsabilidad de ejecutar, gestionar o asegurar la realización de una actividad determinada.",
    simpleDefinition: "A quién le queda la pelota de que algo se haga.",
    avenidaExample: "El responsable de verificar la eficacia de una Acción Correctiva antes de que se la pueda cerrar.",
    whyItMatters: "Sin un responsable claro, una acción queda \"en el aire\" y nadie se hace cargo de que avance.",
    whatToDoIfDetected: "Se asigna al cargar cada registro de gestión, riesgo, objetivo o indicador.",
    relatedIds: ["aprobador"],
  },
  {
    id: "retrabajo",
    term: "Retrabajo",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Actividad realizada nuevamente sobre un resultado para lograr que cumpla con los requisitos establecidos.",
    simpleDefinition: "Volver a hacer algo porque no salió bien la primera vez.",
    avenidaExample: "Reprogramar una funcionalidad porque no cumplía con la especificación funcional acordada.",
    whyItMatters: "Mucho retrabajo repetido en un mismo tipo de tarea suele ser síntoma de una causa raíz sin resolver.",
    whatToDoIfDetected: "Si se repite seguido, vale la pena analizarlo como una No Conformidad recurrente, no solo corregirlo cada vez.",
    relatedIds: ["defecto-bug", "causa-raiz"],
  },
  {
    id: "revision-de-diseno-y-desarrollo",
    term: "Revisión de Diseño y Desarrollo",
    category: "diseno-y-desarrollo",
    technicalDefinition:
      "Evaluación realizada en etapas adecuadas del proceso de Diseño y Desarrollo para analizar sus resultados, avance y capacidad de cumplir los requisitos, así como identificar problemas y determinar las acciones necesarias.",
    simpleDefinition: "Parar a mirar cómo viene el proceso y si va a poder cumplir lo que se pidió — no es lo mismo que verificar o validar el resultado final.",
    avenidaExample: "A mitad del desarrollo de una integración, revisar si el avance permite llegar a la fecha comprometida cumpliendo los requisitos.",
    whyItMatters: "Revisión, Verificación y Validación son tres controles distintos: revisión mira el proceso en curso, verificación confirma que se cumplió lo definido, validación confirma que sirve para lo que se necesitaba.",
    whatToDoIfDetected: "Se planifica en las etapas adecuadas del Diseño y Desarrollo, no solo al final.",
    relatedIds: ["diseno-y-desarrollo", "verificacion", "validacion"],
  },
  {
    id: "salida",
    term: "Salida",
    category: "procesos",
    technicalDefinition: "Resultado generado por un proceso o actividad.",
    simpleDefinition: "Lo que un proceso produce al final.",
    avenidaExample: "La cuenta configurada y la integración funcionando son la salida del proceso de Implementación e Integración con Clientes.",
    whyItMatters: "Pensar en salidas (no solo en tareas) ayuda a definir qué hay que verificar realmente al cerrar un proceso.",
    whatToDoIfDetected: "Se define al describir cada proceso en su ficha correspondiente.",
    relatedIds: ["proceso", "elementos-de-salida-dyd"],
  },
  {
    id: "uat",
    term: "UAT — User Acceptance Testing",
    acronym: "UAT",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Prueba de aceptación destinada a validar que una solución satisface los requisitos y el uso previsto antes de su aceptación o liberación, de acuerdo con el proceso definido.",
    simpleDefinition: "La prueba final donde alguien confirma que la solución realmente sirve para lo que se necesitaba, antes de liberarla.",
    avenidaExample: "El área de Soporte prueba el nuevo panel de liquidaciones antes de que se libere a los sellers.",
    whyItMatters: "Es una de las formas concretas de Validación — sin UAT, se puede liberar algo técnicamente correcto pero que no resuelve la necesidad real.",
    whatToDoIfDetected: "Su resultado queda como registro de UAT antes del deploy.",
    relatedIds: ["validacion", "deploy", "registro"],
  },
  {
    id: "ux",
    term: "UX — User Experience",
    acronym: "UX",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Disciplina orientada al diseño y evaluación de la experiencia que una persona tiene al interactuar con un producto o servicio.",
    simpleDefinition: "Qué tan bien se siente usar lo que construimos, no solo si funciona técnicamente.",
    avenidaExample: "Evaluar si el flujo de alta de un seller es simple de entender y completar, más allá de que funcione sin errores.",
    whyItMatters: "Una solución puede cumplir todos los requisitos funcionales y aun así ser difícil o confusa de usar.",
    whatToDoIfDetected: "Se considera desde el Diseño funcional, no se agrega recién al final.",
    relatedIds: ["ui", "diseno-funcional", "equipo-de-producto"],
  },
  {
    id: "ui",
    term: "UI — User Interface",
    acronym: "UI",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Diseño de los elementos visuales e interactivos mediante los cuales una persona utiliza o interactúa con un producto digital.",
    simpleDefinition: "Lo visual y lo clickeable con lo que la gente interactúa en pantalla.",
    avenidaExample: "El diseño de los botones, formularios y pantallas del panel de liquidaciones.",
    whyItMatters: "Es la capa que la gente efectivamente ve y toca — errores acá afectan directamente la percepción de calidad, aunque el resto funcione bien.",
    whatToDoIfDetected: "Se define junto con el Diseño funcional, a cargo del Equipo de Producto.",
    relatedIds: ["ux", "equipo-de-producto"],
  },
  {
    id: "validacion",
    term: "Validación",
    category: "diseno-y-desarrollo",
    technicalDefinition: "Confirmación, mediante la aportación de evidencia objetiva, de que se han cumplido los requisitos para una utilización o aplicación específica prevista.",
    simpleDefinition: "Confirmar que el resultado sirve para lo que realmente se necesitaba, no solo que cumple lo que se escribió.",
    avenidaExample: "Validar funcionalmente que una solución satisface la necesidad prevista antes de su liberación.",
    whyItMatters:
      "Verificación pregunta \"¿cumple con lo que definimos?\"; Validación pregunta \"¿sirve para lo que hacía falta?\" — un resultado puede pasar la verificación y aun así no servir realmente.",
    whatToDoIfDetected: "Se hace antes de liberar la solución, típicamente a través de un UAT.",
    relatedIds: ["verificacion", "uat", "necesidad"],
  },
];

export function getConceptById(id: string): Concept | undefined {
  return CONCEPTS.find((concept) => concept.id === id);
}

export function getRelatedConcepts(concept: Concept): Concept[] {
  return concept.relatedIds
    .map((id) => getConceptById(id))
    .filter((item): item is Concept => Boolean(item));
}
